import type { Metadata } from "next";
import { Instrument_Sans, Assistant } from "next/font/google";
import "./globals.css";



const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-instrument-sans",
  weight: ["400", "500", "600", "700"], // Choose the weights you need
});

const assistant = Assistant({
  subsets: ["latin"],
  variable: "--font-assistant",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSans.variable} ${assistant.variable} font-ass antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
